development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:bc8a3dcbfc85b0ab33ed9b47d80b60b4@soapfish.redistogo.com:11113/
  channel_prefix: defaceme_production
